export const AUTH_CHANGE = 'AUTH_CHANGE'
export const AUTH_INITIALIZED = 'AUTH_INITIALIZED'
export const AUTH_MODAL_ACTIVE = 'AUTH_MODAL_ACTIVE'
export const CHANGE_TOPIC = 'CHANGE_TOPIC'

export const ADD_SESSION_KEY = 'ADD_SESSION_KEY'
export const CREATE_SESSION_REF_PLACEHOLDER = 'CREATE_SESSION_REF_PLACEHOLDER'
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION'
